image:
  tag: "v5"
  repository: "gcr.io/google-samples/gb-frontend"
  pullPolicy: "IfNotPresent"
ingress:
  path: "/"
  hosts:
  - "chart-example.local"
  annotations: {}
  tls: []
  enabled: false
replicaCount: 3
tolerations: []
service:
  port: 80
  type: "ClusterIP"
containerPort: 80
resources: {}
nodeSelector: {}
affinity: {}
